version: "3.3"

services:
    app:
      build: .
      command: /bin/sh
      tty: true
      stdin_open: true
      volumes:
        - .:/uxie
      ports:
        - "3000:3000"
      container_name: uxie