name: Ruby

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

permissions:
  contents: read

jobs:
  common-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"
          bundler-cache: true

      - name: Install Dependencies
        run: bundle install

  test:
    needs: common-setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: bundle exec rake

  lint:
    needs: common-setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Rubocop
        run: bundle exec rubocop