name: Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  common-setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
    - name: Set up Ruby
      with:
        ruby-version: '3.1.2'
        bundler-cache: true
    - run: bundle install

  test:
    needs: common-setup
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: rspec -fd

  lint:
    needs: common-setup
    runs-on: ubuntu-latest
    steps:
    - name: Run Rubocop
      run: rubocop